### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by LiangAndJing** [LiangAndJing/vue-project#1]
> vue-pro@1.0.0 dev /Users/xiexiaojing/jingWorkSpace/vue-project
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-pro@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-pro@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiexiaojing/.npm/_logs/2019-07-17T10_26_38_020Z-debug.log

**Comment by LiangAndJing** [comment]
![image](https://user-images.githubusercontent.com/24790139/61370053-16239d80-a8c4-11e9-8315-4e7df0bdd2c4.png)
